export const booking = [
    {
        room_name: "Cozy And Dark Room",
        room_img: "/hotel room/cosyroom.jpg",
        dis: "Dark themed room with cozy double bed cloud mattress, centralized AC, multifunction bedside controller, and see-through bathroom.",
        day: "1,500",
        night: "1,500",
        full: "2,500",
    },
    {
        room_name: "Luxury Suite",
        room_img: "/hotel room/luxurysuite.jpg",
        dis: "Spacious luxury suite with king-sized bed, modern decor, private balcony, and a jacuzzi tub.",
        day: "3,000",
        night: "3,500",
        full: "6,000",
    },
    {
        room_name: "Family Room",
        room_img: "/hotel room/familyroom.jpg",
        dis: "Perfect for families, featuring two queen beds, kids' play corner, and a kitchenette.",
        day: "2,500",
        night: "2,800",
        full: "4,800",
    },
    {
        room_name: "Executive Room",
        room_img: "/hotel room/executiveroom.jpg",
        dis: "Modern executive room with work desk, high-speed Wi-Fi, and ergonomic seating.",
        day: "2,000",
        night: "2,500",
        full: "4,000",
    },
    {
        room_name: "Vintage Room",
        room_img: "/hotel room/vintageroom.jpg",
        dis: "Classic room with vintage decor, antique furniture, and a homely vibe.",
        day: "1,800",
        night: "2,000",
        full: "3,500",
    },
    {
        room_name: "Poolside Room",
        room_img: "/hotel room/poolside.jpg",
        dis: "Room with direct pool access, private terrace, and tropical decor.",
        day: "2,200",
        night: "2,500",
        full: "4,200",
    },
    {
        room_name: "Deluxe Room",
        room_img: "/hotel room/deluxe.jpg",
        dis: "Deluxe room with a city view, plush bed, and a fully stocked minibar.",
        day: "2,400",
        night: "2,800",
        full: "5,000",
    },
    {
        room_name: "Honeymoon Suite",
        room_img: "/hotel room/honeymoon.jpg",
        dis: "Romantic suite with rose-themed interiors, private hot tub, and mood lighting.",
        day: "3,500",
        night: "4,000",
        full: "7,000",
    },
    {
        room_name: "Eco-Friendly Room",
        room_img: "/hotel room/eco.jpg",
        dis: "Sustainable design with energy-efficient appliances and bamboo furniture.",
        day: "1,600",
        night: "1,900",
        full: "3,200",
    },
    {
        room_name: "Penthouse Suite",
        room_img: "/hotel room/penthouse.jpg",
        dis: "Top-floor penthouse with panoramic views, rooftop garden, and private bar.",
        day: "5,000",
        night: "6,000",
        full: "10,000",
    },
    {
        room_name: "Minimalist Room",
        room_img: "/hotel room/minimalist.jpg",
        dis: "Minimalist design with clean lines, neutral tones, and open space.",
        day: "1,700",
        night: "2,000",
        full: "3,400",
    },
    {
        room_name: "Business Suite",
        room_img: "/hotel room/business.jpg",
        dis: "Suite tailored for business travelers with meeting space, printer, and video conferencing tools.",
        day: "3,000",
        night: "3,500",
        full: "6,000",
    },
    {
        room_name: "Ocean View Room",
        room_img: "/hotel room/oceanview.jpg",
        dis: "Room with stunning ocean views, floor-to-ceiling windows, and a breezy balcony.",
        day: "2,800",
        night: "3,200",
        full: "5,600",
    },
    {
        room_name: "Artistic Room",
        room_img: "/hotel room/artistic.jpg",
        dis: "Art-inspired room with murals, artistic furniture, and a cozy reading nook.",
        day: "1,900",
        night: "2,200",
        full: "3,800",
    },
    {
        room_name: "Cabana Room",
        room_img: "/hotel room/cabana.jpg",
        dis: "Beachside cabana-style room with tropical vibes, hammock, and private lounge.",
        day: "2,600",
        night: "3,000",
        full: "5,000",
    },
    {
        room_name: "Loft Room",
        room_img: "/hotel room/loft.jpg",
        dis: "Stylish loft with high ceilings, industrial decor, and cityscape views.",
        day: "2,200",
        night: "2,500",
        full: "4,200",
    },
    {
        room_name: "Royal Suite",
        room_img: "/hotel room/royalsuite.jpg",
        dis: "Grand suite with royal decor, four-poster bed, private butler service, and gold accents.",
        day: "6,000",
        night: "7,500",
        full: "12,000",
    },
    {
        room_name: "Themed Room",
        room_img: "/hotel room/themed.jpg",
        dis: "Themed room with unique decor like jungle, space, or retro designs.",
        day: "2,000",
        night: "2,400",
        full: "4,000",
    },
    {
        room_name: "Skyline Suite",
        room_img: "/hotel room/skyline.jpg",
        dis: "Luxury suite with panoramic city skyline views and premium amenities.",
        day: "4,000",
        night: "5,000",
        full: "8,000",
    },
    {
        room_name: "Pet-Friendly Room",
        room_img: "/hotel room/petfriendly.jpg",
        dis: "Comfortable room with pet beds, toys, and an outdoor pet play area.",
        day: "1,800",
        night: "2,200",
        full: "3,600",
    },
];
