export const trip = [
    {
        place_name: "Belgium",
        place_img: "/trip/belgium.jpg",
        dis: "Explore the heart of Europe with a trip to Belgium! Discover the medieval charm of Bruges, the vibrant culture of Brussels, and the historic beauty of Ghent. Indulge in world-famous Belgian chocolates, waffles, and beers, and marvel at iconic landmarks like the Atomium and Grand Place. Whether it’s art, history, or gastronomy, Belgium offers a perfect blend of experiences for every traveler.",
        duration: "3Days/4Night",
        price: "20,000",
    },
    {
        place_name: "Switzerland",
        place_img: "/trip/switzerland.jpg",
        dis: "Experience the stunning Alps, serene lakes, and charming villages in Switzerland. Visit iconic spots like Interlaken, Lucerne, and Zermatt while indulging in Swiss chocolates and cheese.",
        duration: "5Days/6Night",
        price: "45,000",
    },
    {
        place_name: "Paris, France",
        place_img: "/trip/paris.jpg",
        dis: "Visit the city of love and lights, Paris! Explore the Eiffel Tower, Louvre Museum, and charming streets of Montmartre. Enjoy world-class cuisine and a romantic Seine River cruise.",
        duration: "4Days/5Night",
        price: "30,000",
    },
    {
        place_name: "Maldives",
        place_img: "/trip/maldives.jpg",
        dis: "Relax in the tropical paradise of the Maldives, with white sandy beaches, crystal-clear waters, and luxurious overwater villas. Perfect for a romantic or rejuvenating getaway.",
        duration: "4Days/5Night",
        price: "50,000",
    },
    {
        place_name: "Bali, Indonesia",
        place_img: "/trip/bali.jpg",
        dis: "Discover the cultural and natural beauty of Bali. Visit rice terraces, ancient temples, and pristine beaches while enjoying traditional Balinese cuisine and spas.",
        duration: "5Days/6Night",
        price: "40,000",
    },
    {
        place_name: "Dubai, UAE",
        place_img: "/trip/dubai.jpg",
        dis: "Explore the ultra-modern city of Dubai with its skyscrapers, luxury shopping, and desert adventures. Visit the Burj Khalifa, Dubai Mall, and Palm Jumeirah.",
        duration: "3Days/4Night",
        price: "25,000",
    },
    {
        place_name: "Rome, Italy",
        place_img: "/trip/rome.jpg",
        dis: "Step into history with a trip to Rome. Explore ancient landmarks like the Colosseum, Roman Forum, and Vatican City, and indulge in authentic Italian cuisine.",
        duration: "4Days/5Night",
        price: "35,000",
    },
    {
        place_name: "Tokyo, Japan",
        place_img: "/trip/tokyo.jpg",
        dis: "Experience the vibrant culture of Tokyo, blending tradition and technology. Visit temples, bustling markets, and cutting-edge districts like Shibuya and Akihabara.",
        duration: "6Days/7Night",
        price: "60,000",
    },
    {
        place_name: "New York City, USA",
        place_img: "/trip/nyc.jpg",
        dis: "Visit the Big Apple and explore iconic attractions like Times Square, Statue of Liberty, Central Park, and Broadway. Experience the city's vibrant culture and food scene.",
        duration: "5Days/6Night",
        price: "70,000",
    },
    {
        place_name: "Santorini, Greece",
        place_img: "/trip/santorini.jpg",
        dis: "Relax in the picturesque island of Santorini with its iconic white-washed buildings, stunning sunsets, and crystal-clear waters.",
        duration: "3Days/4Night",
        price: "30,000",
    },
    {
        place_name: "London, England",
        place_img: "/trip/london.jpg",
        dis: "Explore the historic and modern wonders of London, from Buckingham Palace to the London Eye, and enjoy the city's diverse food and culture.",
        duration: "4Days/5Night",
        price: "40,000",
    },
    {
        place_name: "Sydney, Australia",
        place_img: "/trip/sydney.jpg",
        dis: "Visit Sydney to see the iconic Opera House, Harbor Bridge, and Bondi Beach. Enjoy Australia's vibrant culture and natural beauty.",
        duration: "6Days/7Night",
        price: "65,000",
    },
    {
        place_name: "Istanbul, Turkey",
        place_img: "/trip/istanbul.jpg",
        dis: "Discover the cultural crossroads of Istanbul, where East meets West. Visit Hagia Sophia, the Blue Mosque, and the Grand Bazaar.",
        duration: "3Days/4Night",
        price: "25,000",
    },
    {
        place_name: "Prague, Czech Republic",
        place_img: "/trip/prague.jpg",
        dis: "Explore the fairy-tale charm of Prague with its historic castles, Charles Bridge, and cobblestone streets. A perfect destination for history lovers.",
        duration: "3Days/4Night",
        price: "22,000",
    },
    {
        place_name: "Bangkok, Thailand",
        place_img: "/trip/bangkok.jpg",
        dis: "Experience the vibrant culture of Bangkok with its ornate temples, bustling street markets, and a cruise along the Chao Phraya River.",
        duration: "4Days/5Night",
        price: "20,000",
    },
    {
        place_name: "Cape Town, South Africa",
        place_img: "/trip/capetown.jpg",
        dis: "Discover the beauty of Cape Town with Table Mountain, Robben Island, and stunning coastal scenery.",
        duration: "5Days/6Night",
        price: "50,000",
    },
    {
        place_name: "Singapore",
        place_img: "/trip/singapore.jpg",
        dis: "Explore the futuristic city of Singapore with its Gardens by the Bay, Marina Bay Sands, and vibrant cultural districts.",
        duration: "3Days/4Night",
        price: "30,000",
    },
    {
        place_name: "Kyoto, Japan",
        place_img: "/trip/kyoto.jpg",
        dis: "Discover the cultural heart of Japan in Kyoto, with its ancient temples, stunning gardens, and traditional tea ceremonies.",
        duration: "4Days/5Night",
        price: "50,000",
    },
    {
        place_name: "Amsterdam, Netherlands",
        place_img: "/trip/amsterdam.jpg",
        dis: "Cruise along the canals of Amsterdam, visit the Van Gogh Museum, and explore the city's charming streets and tulip fields.",
        duration: "3Days/4Night",
        price: "25,000",
    },
    {
        place_name: "Marrakech, Morocco",
        place_img: "/trip/marrakech.jpg",
        dis: "Immerse yourself in the vibrant culture of Marrakech with its bustling souks, historic palaces, and the stunning Atlas Mountains.",
        duration: "4Days/5Night",
        price: "35,000",
    },
];